### ISSUE TITLE
求大佬的指导。

### ISSUE THREAD

**Issue by sanyuequan** [fireinrain/asmr-downloader#10]
大佬，新版本还是报错，请问是需要配置网络环境还是缺少依赖？我用win10，win11 v2ray全局和跳过大陆 裸连都试过了都是报错，求大佬的指导。
2023-11-10T14:08:39.961+0800    ERROR   尝试访问asmr.one失败:   {"error": "Get \"https://asmr.one\": read tcp 192.168.10.2:10443->104.19.15.48:443: wsarecv: An existing connection was forcibly closed by the remote host."}
2023-11-10T14:08:39.965+0800    INFO    当前使用asmr-200.com访问
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x73ec12]

goroutine 1 [running]:
asmr-downloader/config.init.0()
        /home/runner/work/asmr-downloader/asmr-downloader/config/config.go:42 +0x312

**Comment by fireinrain** [comment]
你好 我看了一下你这个报错 很大概率是网络代理问题，我目前使用macos 测试，就是从我这个release页面下载的编译版本，使用clash for windows mac版本 启用tun模式。运行图如下：
<img width="794" alt="image" src="https://github.com/fireinrain/asmr-downloader/assets/14249262/889c271e-04cd-4dba-9b79-06b78b770d69">
<img width="794" alt="image" src="https://github.com/fireinrain/asmr-downloader/assets/14249262/623c2986-02a5-493c-8916-47e1f9a9ef00">

可以看到是可以正常运行的，所以 你需要好好检查一下你这边的网络代理。

**Comment by sanyuequan** [comment]
好的，谢谢大佬
