### ISSUE TITLE
增加服务器地区的选择

### ISSUE THREAD

**Issue by tang-bai** [fireinrain/asmr-downloader#12]
![image](https://github.com/fireinrain/asmr-downloader/assets/71223830/11c5c493-9285-45bb-a25a-fc382e58173c)
目前asmr-100.com这个地址是被墙的但是另外的地址在国内联通和电信都是可以正常连接的

**Comment by tang-bai** [comment]
刚刚看了一下正常来说应该会自动切换成其他网站但是我实际电信网络测试不会切换到asmr-200.com这个域名还是会去连接100这个域名

**Comment by tang-bai** [comment]
![image](https://github.com/fireinrain/asmr-downloader/assets/71223830/529e922f-2f55-40cb-a48e-def36837251b)
我自己手动改了一下config.go电信网络可以直接裸连了

**Comment by fireinrain** [comment]
谢谢你的反馈，我会优化一下。

**Comment by fireinrain** [comment]
最新版本已经添加了在最新域名发布页面获取能够访问的url了。
