### ISSUE TITLE
[建议]之后可能考虑增加DVTAG的功能吗

### ISSUE THREAD

**Issue by tang-bai** [fireinrain/asmr-downloader#13]
DVTAG
https://github.com/NobeKanai/dvtag
dvtag可以自动为音声文件打上正确的标签可以用于更好的分类
如果有FFmpeg可以同时为wav文件转码可以大幅度减少文件体积的占用

**Comment by fireinrain** [comment]
支持wav转mp3的话 需要ffmpeg的支持，感觉对于小工具来说依赖有点大

**Comment by tang-bai** [comment]
并不需要内置ffmpeg只需要提供一个可选项在文档里面说明一下
毕竟一个wav需要占用200-300mb左右转码之后只需要40-50mb左右可以更好的利用储存空间
个人感觉这比直接过滤掉wav文件这个解决办法更好
