### ISSUE TITLE
求教大佬，能够访问https://as.mr/但软件闪退

### ISSUE THREAD

**Issue by vemon2233** [fireinrain/asmr-downloader#15]
开了魔法，然后直接访问https://as.mr/地址能够进入地址页
但是asmr-downloader日志显示进不去这个地址
请问应如何解决，谢谢

**Comment by fireinrain** [comment]
你直接访问 是在浏览器 这样默认应该是命中代理的，至于软件显示 是软件没走代理，你需要做的就是
1. 要么把魔法设置为tun模式，让全局流量走梯子  这样软件也会走梯子
2. 或者 你指定好你本地的系统代理地址，设置好代理的环境遍历，软件会使用系统代理

**Comment by vemon2233** [comment]
谢谢大佬指点。
但我之前确实开启了系统代理，依旧不行
在一番探寻之后在clash的TUN模式管理中从gvisor改为了system就能访问了
原理还是不太懂。。。

**Comment by vemon2233** [comment]
开心，开始睡觉，非常感谢大佬的工作

**Comment by vemon2233** [comment]
另外能请教一个问题吗，软件是如何判定某个作品已经下载过了呢？

**Comment by fireinrain** [comment]
如果你确实下载过，那么会记录到一个数据库中 在本地。如果后面你把作品移到其他地方 软件是不会记录到你的位置的
也就是说 如果某个作品 确实是通过这个软件下载的，会被记录下来
