### ISSUE TITLE
RJ号命名出问题

### ISSUE THREAD

**Issue by vemon2233** [fireinrain/asmr-downloader#16]
目前我开自动下载，得到了一些作品
但是我发现RJ号与as.mr网站及dlsite对不上
目前我的data文件夹中包括两种类型的RJ号文件夹
一种是如RJ100000001-RJ100000013
另一种是如RJ1171092（应为RJ01171092）
请问这两种命名是否均为bug？

**Comment by fireinrain** [comment]
你好  谢谢反馈 对不上 能否给出具体对比  方便我上去排查一下

**Comment by vemon2233** [comment]
第一个问题：
我尝试重新运行软件，发现爬取过程中就会爬取到如RJ100000001-RJ100000039的数据（请见倒数第6行往上）
（整个日志里只有这些RJ1开头的，后面日志里是没有的）
这个RJ号对应的是一些BJ开头的内容比如我找到RJ100000004对应的是BJ01009722

{"L":"INFO","T":"2024-04-24T21:31:01.873+0800","M":"------ASMR.ONE Downloader------"}
{"L":"INFO","T":"2024-04-24T21:31:01.873+0800","M":"---------Power by Euler--------"}
{"L":"INFO","T":"2024-04-24T21:31:01.882+0800","M":"---------version20230207--------"}
{"L":"INFO","T":"2024-04-24T21:31:01.883+0800","M":"检测到初次运行,请进行相关设置..."}
{"L":"INFO","T":"2024-04-24T21:31:01.883+0800","M":"请输入您的账号(默认为guest): "}
{"L":"INFO","T":"2024-04-24T21:31:26.749+0800","M":"请输入您的密码(默认为guest): "}
{"L":"INFO","T":"2024-04-24T21:31:32.143+0800","M":"请输入并发下载数(默认为6): "}
{"L":"INFO","T":"2024-04-24T21:31:33.822+0800","M":"请输入文件下载失败时最大重试次数(默认为3): "}
{"L":"INFO","T":"2024-04-24T21:31:34.207+0800","M":"请输出批量下载作品数量(默认为1): "}
{"L":"INFO","T":"2024-04-24T21:31:34.581+0800","M":"请输出批量下载间隔，单位为秒(默认为1): "}
{"L":"INFO","T":"2024-04-24T21:31:35.506+0800","M":"是否自动执行下一批次下载(Y/N)(默认为N): "}
{"L":"INFO","T":"2024-04-24T21:31:40.460+0800","M":"请输入数据下载目录(默认为data): "}
{"L":"INFO","T":"2024-04-24T21:31:41.948+0800","M":"设置的下载目录不存在,尝试自动生成: data"}
{"L":"INFO","T":"2024-04-24T21:31:41.958+0800","M":"已生成配置文件config.json, 如果您之前不做任何输入，默认以访客模式访问。"}
{"L":"INFO","T":"2024-04-24T21:31:42.015+0800","M":"","info":"GlobalConfig={\"account\":\"vemon233\",\"password\":\"************\",\"max_worker\":6,\"batch_task_count\":1,\"batch_sleep_time\":2,\"auto_for_next_batch\":false,\"download_dir\":\"data\",\"meta_data_db\":\"asmr.db\",\"max_failed_retry\":3}"}
{"L":"INFO","T":"2024-04-24T21:31:43.059+0800","M":"账号登录成功!"}
{"L":"INFO","T":"2024-04-24T21:31:44.262+0800","M":"当前时间: 2024-04-24 21:31:44,网站有新作品更新,正在进行更新..."}
{"L":"INFO","T":"2024-04-24T21:31:44.600+0800","M":"正在获取作品元数据..."}
{"L":"INFO","T":"2024-04-24T21:31:49.262+0800","M":"元数据处理中..."}
{"L":"INFO","T":"2024-04-24T21:31:49.298+0800","M":"新增数据: RJ1173161"}
{"L":"INFO","T":"2024-04-24T21:31:49.309+0800","M":"新增数据: RJ1173153"}
{"L":"INFO","T":"2024-04-24T21:31:49.321+0800","M":"新增数据: RJ1173079"}
{"L":"INFO","T":"2024-04-24T21:31:49.333+0800","M":"新增数据: RJ1173071"}
{"L":"INFO","T":"2024-04-24T21:31:49.345+0800","M":"新增数据: RJ1173042"}
{"L":"INFO","T":"2024-04-24T21:31:49.357+0800","M":"新增数据: RJ1172952"}
{"L":"INFO","T":"2024-04-24T21:31:49.368+0800","M":"新增数据: RJ1172949"}
{"L":"INFO","T":"2024-04-24T21:31:49.379+0800","M":"新增数据: RJ1172929"}
{"L":"INFO","T":"2024-04-24T21:31:49.391+0800","M":"新增数据: RJ1172877"}
{"L":"INFO","T":"2024-04-24T21:31:49.403+0800","M":"新增数据: RJ1172785"}
{"L":"INFO","T":"2024-04-24T21:31:49.412+0800","M":"新增数据: RJ1172782"}
{"L":"INFO","T":"2024-04-24T21:31:49.423+0800","M":"新增数据: RJ1172779"}
{"L":"INFO","T":"2024-04-24T21:31:49.434+0800","M":"新增数据: RJ1172776"}
{"L":"INFO","T":"2024-04-24T21:31:49.446+0800","M":"新增数据: RJ1172773"}
{"L":"INFO","T":"2024-04-24T21:31:49.457+0800","M":"新增数据: RJ1172768"}
{"L":"INFO","T":"2024-04-24T21:31:49.469+0800","M":"新增数据: RJ1172758"}
{"L":"INFO","T":"2024-04-24T21:31:49.480+0800","M":"新增数据: RJ1172687"}
{"L":"INFO","T":"2024-04-24T21:31:49.492+0800","M":"新增数据: RJ1172678"}
{"L":"INFO","T":"2024-04-24T21:31:49.502+0800","M":"新增数据: RJ1172553"}
{"L":"INFO","T":"2024-04-24T21:31:49.513+0800","M":"新增数据: RJ1172515"}
{"L":"INFO","T":"2024-04-24T21:31:49.525+0800","M":"新增数据: RJ1175599"}
{"L":"INFO","T":"2024-04-24T21:31:49.537+0800","M":"新增数据: RJ1175488"}
{"L":"INFO","T":"2024-04-24T21:31:49.548+0800","M":"新增数据: RJ1174938"}
{"L":"INFO","T":"2024-04-24T21:31:49.561+0800","M":"新增数据: RJ1174937"}
{"L":"INFO","T":"2024-04-24T21:31:49.573+0800","M":"新增数据: RJ1174930"}
{"L":"INFO","T":"2024-04-24T21:31:49.584+0800","M":"新增数据: RJ1174529"}
{"L":"INFO","T":"2024-04-24T21:31:49.597+0800","M":"新增数据: RJ1174088"}
{"L":"INFO","T":"2024-04-24T21:31:49.609+0800","M":"新增数据: RJ1173927"}
{"L":"INFO","T":"2024-04-24T21:31:49.619+0800","M":"新增数据: RJ1173680"}
{"L":"INFO","T":"2024-04-24T21:31:49.631+0800","M":"新增数据: RJ1173677"}
{"L":"INFO","T":"2024-04-24T21:31:49.643+0800","M":"新增数据: RJ1173671"}
{"L":"INFO","T":"2024-04-24T21:31:49.654+0800","M":"新增数据: RJ1173669"}
{"L":"INFO","T":"2024-04-24T21:31:49.665+0800","M":"新增数据: RJ1173545"}
{"L":"INFO","T":"2024-04-24T21:31:49.676+0800","M":"新增数据: RJ1173530"}
{"L":"INFO","T":"2024-04-24T21:31:49.687+0800","M":"新增数据: RJ1173486"}
{"L":"INFO","T":"2024-04-24T21:31:49.698+0800","M":"新增数据: RJ1173406"}
{"L":"INFO","T":"2024-04-24T21:31:49.709+0800","M":"新增数据: RJ1173390"}
{"L":"INFO","T":"2024-04-24T21:31:49.720+0800","M":"新增数据: RJ1173336"}
{"L":"INFO","T":"2024-04-24T21:31:49.730+0800","M":"新增数据: RJ1173247"}
{"L":"INFO","T":"2024-04-24T21:31:49.741+0800","M":"新增数据: RJ1173165"}
{"L":"INFO","T":"2024-04-24T21:31:49.752+0800","M":"新增数据: RJ1172409"}
{"L":"INFO","T":"2024-04-24T21:31:49.764+0800","M":"新增数据: RJ1172349"}
{"L":"INFO","T":"2024-04-24T21:31:49.775+0800","M":"新增数据: RJ1172330"}
{"L":"INFO","T":"2024-04-24T21:31:49.786+0800","M":"新增数据: RJ1172323"}
{"L":"INFO","T":"2024-04-24T21:31:49.797+0800","M":"新增数据: RJ1172303"}
{"L":"INFO","T":"2024-04-24T21:31:49.808+0800","M":"新增数据: RJ1172279"}
{"L":"INFO","T":"2024-04-24T21:31:49.819+0800","M":"新增数据: RJ1172255"}
{"L":"INFO","T":"2024-04-24T21:31:49.830+0800","M":"新增数据: RJ1172229"}
{"L":"INFO","T":"2024-04-24T21:31:49.841+0800","M":"新增数据: RJ1172183"}
{"L":"INFO","T":"2024-04-24T21:31:49.853+0800","M":"新增数据: RJ1172171"}
{"L":"INFO","T":"2024-04-24T21:31:49.864+0800","M":"新增数据: RJ1172112"}
{"L":"INFO","T":"2024-04-24T21:31:49.875+0800","M":"新增数据: RJ1172109"}
{"L":"INFO","T":"2024-04-24T21:31:49.887+0800","M":"新增数据: RJ1172073"}
{"L":"INFO","T":"2024-04-24T21:31:49.899+0800","M":"新增数据: RJ1172035"}
{"L":"INFO","T":"2024-04-24T21:31:49.911+0800","M":"新增数据: RJ1171993"}
{"L":"INFO","T":"2024-04-24T21:31:49.926+0800","M":"新增数据: RJ1171989"}
{"L":"INFO","T":"2024-04-24T21:31:49.938+0800","M":"新增数据: RJ1171931"}
{"L":"INFO","T":"2024-04-24T21:31:49.949+0800","M":"新增数据: RJ1171901"}
{"L":"INFO","T":"2024-04-24T21:31:49.959+0800","M":"新增数据: RJ1171884"}
{"L":"INFO","T":"2024-04-24T21:31:49.971+0800","M":"新增数据: RJ1171879"}
{"L":"INFO","T":"2024-04-24T21:31:49.982+0800","M":"新增数据: RJ100000039"}
{"L":"INFO","T":"2024-04-24T21:31:49.993+0800","M":"新增数据: RJ100000038"}
{"L":"INFO","T":"2024-04-24T21:31:50.004+0800","M":"新增数据: RJ100000037"}
{"L":"INFO","T":"2024-04-24T21:31:50.016+0800","M":"新增数据: RJ100000036"}
{"L":"INFO","T":"2024-04-24T21:31:50.025+0800","M":"新增数据: RJ100000035"}
{"L":"INFO","T":"2024-04-24T21:31:50.037+0800","M":"新增数据: RJ100000034"}
{"L":"INFO","T":"2024-04-24T21:31:50.050+0800","M":"新增数据: RJ100000033"}
{"L":"INFO","T":"2024-04-24T21:31:50.061+0800","M":"新增数据: RJ100000032"}
{"L":"INFO","T":"2024-04-24T21:31:50.072+0800","M":"新增数据: RJ100000031"}
{"L":"INFO","T":"2024-04-24T21:31:50.082+0800","M":"新增数据: RJ100000030"}
{"L":"INFO","T":"2024-04-24T21:31:50.094+0800","M":"新增数据: RJ100000029"}
{"L":"INFO","T":"2024-04-24T21:31:50.105+0800","M":"新增数据: RJ100000028"}
{"L":"INFO","T":"2024-04-24T21:31:50.116+0800","M":"新增数据: RJ100000027"}
{"L":"INFO","T":"2024-04-24T21:31:50.127+0800","M":"新增数据: RJ100000026"}
{"L":"INFO","T":"2024-04-24T21:31:50.139+0800","M":"新增数据: RJ100000025"}
{"L":"INFO","T":"2024-04-24T21:31:50.150+0800","M":"新增数据: RJ100000024"}
{"L":"INFO","T":"2024-04-24T21:31:50.160+0800","M":"新增数据: RJ100000023"}
{"L":"INFO","T":"2024-04-24T21:31:50.172+0800","M":"新增数据: RJ100000022"}
{"L":"INFO","T":"2024-04-24T21:31:50.183+0800","M":"新增数据: RJ100000021"}
{"L":"INFO","T":"2024-04-24T21:31:50.195+0800","M":"新增数据: RJ100000020"}
{"L":"INFO","T":"2024-04-24T21:31:50.206+0800","M":"新增数据: RJ100000019"}
{"L":"INFO","T":"2024-04-24T21:31:50.216+0800","M":"新增数据: RJ100000018"}
{"L":"INFO","T":"2024-04-24T21:31:50.233+0800","M":"新增数据: RJ100000017"}
{"L":"INFO","T":"2024-04-24T21:31:50.245+0800","M":"新增数据: RJ100000016"}
{"L":"INFO","T":"2024-04-24T21:31:50.248+0800","M":"新增数据: RJ100000015"}
{"L":"INFO","T":"2024-04-24T21:31:50.251+0800","M":"新增数据: RJ100000014"}
{"L":"INFO","T":"2024-04-24T21:31:50.255+0800","M":"新增数据: RJ100000013"}
{"L":"INFO","T":"2024-04-24T21:31:50.258+0800","M":"新增数据: RJ100000012"}
{"L":"INFO","T":"2024-04-24T21:31:50.261+0800","M":"新增数据: RJ100000011"}
{"L":"INFO","T":"2024-04-24T21:31:50.264+0800","M":"新增数据: RJ100000010"}
{"L":"INFO","T":"2024-04-24T21:31:50.268+0800","M":"新增数据: RJ100000009"}
{"L":"INFO","T":"2024-04-24T21:31:50.270+0800","M":"新增数据: RJ100000008"}
{"L":"INFO","T":"2024-04-24T21:31:50.274+0800","M":"新增数据: RJ100000007"}
{"L":"INFO","T":"2024-04-24T21:31:50.277+0800","M":"新增数据: RJ100000006"}
{"L":"INFO","T":"2024-04-24T21:31:50.281+0800","M":"新增数据: RJ100000005"}
{"L":"INFO","T":"2024-04-24T21:31:50.284+0800","M":"新增数据: RJ100000004"}
{"L":"INFO","T":"2024-04-24T21:31:50.287+0800","M":"新增数据: RJ100000003"}
{"L":"INFO","T":"2024-04-24T21:31:50.290+0800","M":"新增数据: RJ100000002"}
{"L":"INFO","T":"2024-04-24T21:31:50.293+0800","M":"新增数据: RJ100000001"}
{"L":"INFO","T":"2024-04-24T21:31:50.297+0800","M":"新增数据: RJ1176462"}
{"L":"INFO","T":"2024-04-24T21:31:50.300+0800","M":"新增数据: RJ1171877"}
{"L":"INFO","T":"2024-04-24T21:31:50.303+0800","M":"新增数据: RJ1171778"}
{"L":"INFO","T":"2024-04-24T21:31:50.307+0800","M":"新增数据: RJ1171762"}
{"L":"INFO","T":"2024-04-24T21:31:50.310+0800","M":"新增数据: RJ1171663"}

**Comment by vemon2233** [comment]
昨天试着看了一下代码，但毕竟没怎么用过go，我python也是个半吊子
没找到应该如何改，还是请大佬出手相助吧

**Comment by fireinrain** [comment]
现在应该修复了
