### ISSUE TITLE
又来打扰，1.4版本闪退

### ISSUE THREAD

**Issue by vemon2233** [fireinrain/asmr-downloader#17]
日志文件如下，请问会不会是改了储存RJ格式导致的报错？
因为我看到数据库里存的数据为(40105, '%!d(string=RJ042205)', '42205', 0, '*****', 0)

{"L":"INFO","T":"2024-04-25T21:51:10.524+0800","M":"当前使用as.mr访问最新站点发布页..."}
{"L":"INFO","T":"2024-04-25T21:51:12.411+0800","M":"Checking Fast Response:","response":"https://asmr.one/|759.8007ms"}
{"L":"INFO","T":"2024-04-25T21:51:12.434+0800","M":"Checking Fast Response:","response":"https://asmr-200.com/|783.2541ms"}
{"L":"INFO","T":"2024-04-25T21:51:12.443+0800","M":"Checking Fast Response:","response":"https://asmr-300.com/|792.6049ms"}
{"L":"INFO","T":"2024-04-25T21:51:12.490+0800","M":"Checking Fast Response:","response":"https://asmr-100.com/|839.2818ms"}
{"L":"INFO","T":"2024-04-25T21:51:12.490+0800","M":"Fastest Response is:","response":"https://asmr.one/|759.8007ms"}
{"L":"INFO","T":"2024-04-25T21:51:12.500+0800","M":"------ASMR.ONE Downloader------"}
{"L":"INFO","T":"2024-04-25T21:51:12.500+0800","M":"---------Power by Euler--------"}
{"L":"INFO","T":"2024-04-25T21:51:12.500+0800","M":"---------version20230207--------"}
{"L":"INFO","T":"2024-04-25T21:51:12.500+0800","M":"程序已初始化完成,正在启动运行..."}
{"L":"INFO","T":"2024-04-25T21:51:12.502+0800","M":"","info":"GlobalConfig={\"account\":\"vemon233\",\"password\":\"************\",\"max_worker\":6,\"batch_task_count\":1,\"batch_sleep_time\":1,\"auto_for_next_batch\":false,\"download_dir\":\"data\",\"meta_data_db\":\"asmr.db\",\"max_failed_retry\":3}"}
{"L":"INFO","T":"2024-04-25T21:51:13.513+0800","M":"账号登录成功!"}
{"L":"INFO","T":"2024-04-25T21:51:14.808+0800","M":"当前时间: 2024-04-25 21:51:14,网站暂时无新作品..."}
{"L":"INFO","T":"2024-04-25T21:51:14.890+0800","M":"\n----------------------\n当前时间: 2024-04-25 21:51:14\n作品总数: 40275部\n含字幕作品数: 2780部\n含字幕作品已下载数: 0部\n无字幕作品数: 37495部\n无字幕作品已下载数: 0部\n含字幕作品下载进度: 0.00%\n无字幕作品下载进度: 0.00%\n总下载进度: 0.00%"}
{"L":"INFO","T":"2024-04-25T21:51:14.890+0800","M":"ASMR作品本地与网站不同步.是否需要同步下载(Y/N,默认为Y)?:"}
{"L":"INFO","T":"2024-04-25T21:51:17.079+0800","M":"正在下载ASMR作品文件,请稍后..."}
{"L":"INFO","T":"2024-04-25T21:51:17.079+0800","M":"作品 RJ 号: ","info":"RJ%!d(string=01172171)"}

**Comment by vemon2233** [comment]
另外有个无关的问题，我自己试着去运行源代码去查找原因，但是编译报错，几经查找未能解决，大佬是否能帮忙看下，十分感谢
# modernc.org/sqlite/lib
C:\Users\10043\go\pkg\mod\modernc.org\sqlite@v1.27.0\lib\defs.go:13:35: undefined: sqlite3_index_constraint
C:\Users\10043\go\pkg\mod\modernc.org\sqlite@v1.27.0\lib\defs.go:14:35: undefined: sqlite3_index_orderby
C:\Users\10043\go\pkg\mod\modernc.org\sqlite@v1.27.0\lib\defs.go:15:35: undefined: sqlite3_index_constraint_usage
C:\Users\10043\go\pkg\mod\modernc.org\sqlite@v1.27.0\lib\mutex.go:19:5: undefined: Xsqlite3_threadsafe
C:\Users\10043\go\pkg\mod\modernc.org\sqlite@v1.27.0\lib\mutex.go:29:11: undefined: Xsqlite3_config
C:\Users\10043\go\pkg\mod\modernc.org\sqlite@v1.27.0\lib\mutex.go:29:32: undefined: SQLITE_CONFIG_MUTEX
C:\Users\10043\go\pkg\mod\modernc.org\sqlite@v1.27.0\lib\mutex.go:29:122: undefined: SQLITE_OK
C:\Users\10043\go\pkg\mod\modernc.org\sqlite@v1.27.0\lib\mutex.go:30:8: undefined: Xsqlite3_errstr
C:\Users\10043\go\pkg\mod\modernc.org\sqlite@v1.27.0\lib\mutex.go:40:17: undefined: Sqlite3_mutex_methods
C:\Users\10043\go\pkg\mod\modernc.org\sqlite@v1.27.0\lib\mutex.go:239:46: undefined: SQLITE_OK
C:\Users\10043\go\pkg\mod\modernc.org\sqlite@v1.27.0\lib\mutex.go:239:46: too many errors

**Comment by fireinrain** [comment]
我刚才解决了一下 现在没问题了 我本地mac可以跑起来 v1.4.1
至于你debug 是因为你没下载依赖  下载依赖需要梯子环境 否则下载不到依赖

**Comment by vemon2233** [comment]
出现了这样的问题，删掉failed-download.txt之后依旧会出现同样的报错，以管理员运行也不行，劳烦大佬再看一下


{"L":"INFO","T":"2024-04-26T18:40:15.342+0800","M":"ASMR作品本地与网站不同步.是否需要同步下载(Y/N,默认为Y)?:"}
{"L":"INFO","T":"2024-04-26T18:40:17.122+0800","M":"正在下载ASMR作品文件,请稍后..."}
{"L":"INFO","T":"2024-04-26T18:40:17.122+0800","M":"作品 RJ 号: ","info":"RJVJ014780"}
{"L":"INFO","T":"2024-04-26T18:40:17.428+0800","M":"无字幕数据: VJ014780 下载完成..."}
{"L":"INFO","T":"2024-04-26T18:40:17.428+0800","M":"--------------------为下一批次下载休眠--------------------"}
{"L":"INFO","T":"2024-04-26T18:40:19.442+0800","M":"正在自动处理下载失败的媒体文件,请稍后..."}
{"L":"ERROR","T":"2024-04-26T18:40:19.473+0800","M":"清空下载失败日志文件失败:","error":"truncate failed-download.txt: Access is denied."}
{"L":"INFO","T":"2024-04-26T18:40:19.476+0800","M":"手动确认下一批次任务,按回车键继续进行任务: "}
{"L":"INFO","T":"2024-04-26T18:40:20.738+0800","M":"作品 RJ 号: ","info":"RJVJ014682"}
{"L":"INFO","T":"2024-04-26T18:40:21.429+0800","M":"无字幕数据: VJ014682 下载完成..."}
{"L":"INFO","T":"2024-04-26T18:40:21.429+0800","M":"--------------------为下一批次下载休眠--------------------"}
{"L":"INFO","T":"2024-04-26T18:40:23.438+0800","M":"正在自动处理下载失败的媒体文件,请稍后..."}
{"L":"ERROR","T":"2024-04-26T18:40:23.474+0800","M":"清空下载失败日志文件失败:","error":"truncate failed-download.txt: Access is denied."}
{"L":"INFO","T":"2024-04-26T18:40:23.474+0800","M":"手动确认下一批次任务,按回车键继续进行任务: "}
{"L":"INFO","T":"2024-04-26T18:40:23.475+0800","M":"作品 RJ 号: ","info":"RJVJ011122"}
{"L":"INFO","T":"2024-04-26T18:40:23.829+0800","M":"无字幕数据: VJ011122 下载完成..."}
{"L":"INFO","T":"2024-04-26T18:40:23.829+0800","M":"--------------------为下一批次下载休眠--------------------"}
{"L":"INFO","T":"2024-04-26T18:40:25.835+0800","M":"正在自动处理下载失败的媒体文件,请稍后..."}
{"L":"ERROR","T":"2024-04-26T18:40:25.879+0800","M":"清空下载失败日志文件失败:","error":"truncate failed-download.txt: Access is denied."}
{"L":"INFO","T":"2024-04-26T18:40:25.880+0800","M":"手动确认下一批次任务,按回车键继续进行任务: "}

**Comment by vemon2233** [comment]
<img width="338" alt="屏幕截图 2024-04-26 184403" src="https://github.com/fireinrain/asmr-downloader/assets/135819730/3302a8c7-a89e-4a2d-a4e9-4044ba8e1be8">
另外，请看下这个依赖我应该是下好了的吧，sqlite包是有的啊

**Comment by vemon2233** [comment]
帮忙这么多，实在感谢大佬

**Comment by fireinrain** [comment]
现在的版本 应该是能正常运行的

**Comment by fireinrain** [comment]
> 帮忙这么多，实在感谢大佬

go mod tidy 在根目录试一试
