### ISSUE TITLE
1.4.1 无法访问

### ISSUE THREAD

**Issue by luoli233** [fireinrain/asmr-downloader#18]
window版和linux版都提示下面这个，我这里可以确认是能正常访问asmr.one、as.131433.xyz的，只有as.mr无法访问
并且也已经试过开梯子了，一样是这个错误

2024-04-26T02:09:28.178+0800	INFO	尝试访问asmr.one最新站点发布页as.mr失败: 	{"error": "Get \"https://as.mr\": dial tcp [2a03:2880:f10d:183:face:b00c:0:25de]:443: connect: connection timed out"}
2024-04-26T02:09:28.178+0800	INFO	当前使用as.131433.xyz代理访问最新站点发布页
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x696481]

goroutine 1 [running]:
asmr-downloader/config.GetAsmrLatestUrls()
	/home/runner/work/asmr-downloader/asmr-downloader/config/config.go:61 +0x321
asmr-downloader/config.GetRespFastestSiteUrl()
	/home/runner/work/asmr-downloader/asmr-downloader/config/config.go:132 +0x2e
asmr-downloader/config.init.0()
	/home/runner/work/asmr-downloader/asmr-downloader/config/config.go:32 +0x17

**Comment by fireinrain** [comment]
有配置初始信息吗，还有一个就是设置好代理
让这个软件走代理端口 或者梯子开启tun模式
奇怪 我mac版本下 是正常运行的

**Comment by luoli233** [comment]
> 有配置初始信息吗，还有一个就是设置好代理 让这个软件走代理端口 或者梯子开启tun模式 奇怪 我mac版本下 是正常运行的

梯子开启tun模式就正常能用了

**Comment by fireinrain** [comment]
那应该是代理设置的问题了
