### ISSUE TITLE
下载记录显示的已下载数量和实际下载数量对不上

### ISSUE THREAD

**Issue by luoli233** [fireinrain/asmr-downloader#20]
下载记录显示我一共下载了6557个作品，其中无字幕5877，有字幕680
实际我的文件夹只有6425个，其中无字幕作品5757，有字幕668
这完全对不上记录

我用的是kikoeru进行音声管理，设置扫描深度3层，实际识别到6439部作品，还是一样对不上下载记录的6557个

**Comment by fireinrain** [comment]
这个问题以前也想过 后来发现有些数据 他是出现在两边的。。。

**Comment by luoli233** [comment]
> 这个问题以前也想过 后来发现有些数据 他是出现在两边的。。。

确实可能是这样，因为下载过程中我是每批300一次，实际很少会下载满300个，都是会缺几个，有一次还缺了十几个
