### ISSUE TITLE
删除碎片文件失败以及能否不挂梯子下载

### ISSUE THREAD

**Issue by Asvolt** [fireinrain/asmr-downloader#21]
![111](https://github.com/fireinrain/asmr-downloader/assets/122348538/14e29387-0fc9-44f5-9ce7-a393dff821c8)
如图，有部分文件会显示下载失败并且删除碎片文件失败，但是我去asmr.one访问对应文件没问题，不知道是我网的问题还是其他原因导致的

另外，因为启动asmr-downloader要访问asmr.one的发布页，必须让梯子处于tun模式，但是这样下载就会消耗梯子的流量，有没有办法让asmrdownloader在访问最新发布页后以不使用代理的方式进行下载

**Comment by fireinrain** [comment]
因为asmr.one的地址不能保证提供的地址就是没有被墙的。这个不好处理。。。

**Comment by luoli233** [comment]
访问asmr.one的发布页，你可以指定一下hosts就行了 不需要梯子

**Comment by Asvolt** [comment]
> 访问asmr.one的发布页，你可以指定一下hosts就行了 不需要梯子

能不能问一下我具体应该怎么做？

**Comment by luoli233** [comment]
修改hosts教程自己百度
添加这个
104.25.243.36 as.mr

还有删除碎片文件失败应该是win系统的权限问题，程序没有修改文件的权限导致失败记录删不掉，你可以试试用管理员运行程序看看能不能解决

**Comment by Asvolt** [comment]
> 修改hosts教程自己百度 添加这个 104.25.243.36 as.mr
> 
> 还有删除碎片文件失败应该是win系统的权限问题，程序没有修改文件的权限导致失败记录删不掉，你可以试试用管理员运行程序看看能不能解决

改了host之后可以在不挂梯子的情况下启动了
至于删除碎片文件的问题，按控制面板-用户账户里面的设置看，我现在唯一的本地账户就是管理员账户，应该是有权限的吧
![222](https://github.com/fireinrain/asmr-downloader/assets/122348538/d87d111f-f2b8-46fe-8757-fdc2af64d133)
另外我现在下什么都会失败，1.2.7的旧版和1.4.1的新版都是，也不知道是什么原因

**Comment by Asvolt** [comment]
> 修改hosts教程自己百度 添加这个 104.25.243.36 as.mr
> 
> 还有删除碎片文件失败应该是win系统的权限问题，程序没有修改文件的权限导致失败记录删不掉，你可以试试用管理员运行程序看看能不能解决

更正一下，因为之前那个RJ号在网页端打开没有问题，我以为问题出在其他地方，结果换个RJ号就能下载了，另外以管理员身份运行powershell之后下载之前产生删除碎片文件失败的RJ号，删除碎片文件失败的问题还是没有解决

**Comment by Asvolt** [comment]
> 修改hosts教程自己百度 添加这个 104.25.243.36 as.mr
> 
> 还有删除碎片文件失败应该是win系统的权限问题，程序没有修改文件的权限导致失败记录删不掉，你可以试试用管理员运行程序看看能不能解决

再补充一下，我去找了那几个删除文件碎片失败的文件，在网页端可以正常打开，但是右键下载会报ERROR1015
