### ISSUE TITLE
简易模式提示`asmr-downloader.exe' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by xyh2274** [fireinrain/asmr-downloader#3]
`asmr-downloader.exe' 不是内部或外部命令，也不是可运行的程序或批处理文件。
尝配置系统环境标量也不行

**Comment by decblue** [comment]
直接闪退了

**Comment by fireinrain** [comment]
我看一下，最近没测试简易模式

**Comment by fireinrain** [comment]
<img width="653" alt="image" src="https://user-images.githubusercontent.com/14249262/226600450-16e09724-9790-4f1f-bfce-9433ef1c297f.png">
我本地是可以运行的

**Comment by fireinrain** [comment]
> `asmr-downloader.exe' 不是内部或外部命令，也不是可运行的程序或批处理文件。 尝配置系统环境标量也不行

文档多写了字符 你把``删除就可以了，我也更新了文档
