### ISSUE TITLE
闪退问题

### ISSUE THREAD

**Issue by Godeau233** [fireinrain/asmr-downloader#5]
用的win11，程序打开时有的时候是直接闪退，有的时候在运行过程中闪退。
不知道什么情况，修改过兼容模式或是用管理员运行，都会闪退

**Comment by Godeau233** [comment]
没有相关提示

**Comment by fireinrain** [comment]
> 没有相关提示

抱歉我目前的电脑只有win10 和mac，没使用windows11 做过测试

**Comment by Godeau233** [comment]
将上次失败的文件下载完后会显示："清空下载失败日志文件失败:","error":"truncate failed-download.txt: Access is denied."}
