### ISSUE TITLE
在Linux中运行会报错

### ISSUE THREAD

**Issue by Godeau233** [fireinrain/asmr-downloader#7]
在Linux中运行程序会出现
`2023-06-23T20:31:00.248+0800    ERROR   尝试访问asmr.one失败:   {"error": "Get \"https://asmr.one\": read tcp 172.25.198.149:39072->8.210.135.104:443: read: connection reset by peer"}
2023-06-23T20:31:00.249+0800    INFO    当前使用asmr-100.com访问
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6cceb2]

goroutine 1 [running]:
asmr-downloader/config.init.0()
        /home/runner/work/asmr-downloader/asmr-downloader/config/config.go:39 +0x312`

**Comment by fireinrain** [comment]
你好 这个报错很大概率是你本地的网络代理有问题 没法访问到asmr.one这个网站
这是我当前下载的release版本 mac版本运行的结果，本地使用clash for windows 开启tun模式
<img width="794" alt="image" src="https://github.com/fireinrain/asmr-downloader/assets/14249262/2a82eb33-ab44-4360-82c1-e422303beba7">
<img width="794" alt="image" src="https://github.com/fireinrain/asmr-downloader/assets/14249262/ed8d29b9-6ddb-40f0-8640-f912eb34efac">
应该排查一下你这边的代理情况
